server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: user
    username: user
    url: jdbc:mysql://${DB_HOST:localhost}:3306/userdb
  jpa:
    hibernate:
      ddl-auto: create
user:
  min: 18